### ISSUE TITLE
Update Expiration in db

### ISSUE THREAD

**Issue by nicolewert** [mokumoku-lovers/moku-moku-auth#22]

**Comment by nicolewert** [comment]
Need to add Update Expiration to service.go

**Comment by xyzhg** [comment]
Maybe the order of parameters in line `session.Query(queryUpdateExpiration, at.AccessToken, at.TokenExpiration)` should be switched due to the query sentence is `"UPDATE access_tokens SET expires=? WHERE access_token=?;"`

**Comment by JiahuiChen99** [comment]
Yup, I agree, I also think we should swap those 👀
